
matrix:
  include:
    - language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-29
          - build-tools-29.0.2
      before_script:
        - cd app/
      script:
        - ./gradlew test