language: android
dist: trusty
      jdk: oraclejdk8	
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
    - tools
    - android-29
    - build-tools-29.0.2
  before_script:
    - cd app/
  script:
   - ./gradlew build